# Generated by Django 6.0.6 on 2026-07-06 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parshas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("aliya_1", "Aliya 1"),
                            ("aliya_2", "Aliya 2"),
                            ("aliya_3", "Aliya 3"),
                            ("aliya_4", "Aliya 4"),
                            ("aliya_5", "Aliya 5"),
                            ("aliya_6", "Aliya 6"),
                            ("aliya_7", "Aliya 7"),
                            ("maftir", "Maftir"),
                            ("haftorah", "Haftorah"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "parsha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to="parshas.parsha",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "learning progresses",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "parsha", "segment_type"),
                        name="unique_user_parsha_segment",
                    )
                ],
            },
        ),
    ]
