# Generated by Django 6.0.8 on 2026-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=255)),
                ('title_hebrew', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Chumash (Parshas)', 'Chumash (Parshas)'), ('Mon-Thurs Learnings', 'Mon-Thurs Learnings'), ('Yomim Tovim / Special Learnings', 'Yomim Tovim / Special Learnings'), ('Haftoros', 'Haftoros'), ('Megillos', 'Megillos'), ('Nusach HaTefilla', 'Nusach HaTefilla')], max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
