# Generated by Django 6.0.8 on 2026-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='category',
            field=models.CharField(choices=[('Chumash (Parshios)', 'Chumash (Parshios)'), ('Mon-Thurs Lainings', 'Mon-Thurs Lainings'), ('Yomim Tovim / Special Lainings', 'Yomim Tovim / Special Lainings'), ('Haftoros', 'Haftoros'), ('Megillos', 'Megillos'), ('Nusach HaTefilla', 'Nusach HaTefilla')], max_length=100),
        ),
    ]
