# Generated by Django 6.0.8 on 2026-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manager', '0002_alter_audiorecording_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='title_hebrew',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
