# Generated by Django 6.0.6 on 2026-07-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_pro_customuser_referral_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="stripe_customer_id",
            new_name="rc_original_app_user_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="stripe_subscription_id",
        ),
    ]
