# Generated by Django 6.0.6 on 2026-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_rename_stripe_customer_id_customuser_rc_original_app_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
