# Generated by Django 6.0.7 on 2026-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='coachingrequest',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coachingrequest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coachingrequest',
            name='preferred_times',
            field=models.TextField(blank=True, default='', help_text='Preferred times for coaching'),
        ),
    ]
