# Generated by Django 6.0.7 on 2026-07-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_coachingrequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rc_entitlement_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rc_expires_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rc_subscription_status',
            field=models.CharField(blank=True, help_text='e.g. active, expired, trialing', max_length=50, null=True),
        ),
    ]
