# Generated by Django 6.0.8 on 2026-09-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_rc_entitlement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
