# Generated by Django 6.0.8 on 2026-08-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_subs', '0003_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users_and_subs.userprofile'),
        ),
    ]
