# Generated by Django 6.0.8 on 2026-08-12 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaching_type', models.CharField(choices=[('In-person Staten Island', 'In-person Staten Island'), ('In-person Brooklyn', 'In-person Brooklyn'), ('Zoom worldwide', 'Zoom worldwide')], max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_coaching_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coaching Request',
                'verbose_name_plural': 'Coaching Requests',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
            },
        ),
    ]
