# Generated by Django 6.0.6 on 2026-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiotrack",
            name="grouping",
            field=models.CharField(
                blank=True,
                help_text="e.g., Yamim Noraim, Shalosh Regalim, etc.",
                max_length=100,
                null=True,
            ),
        ),
    ]
