# Generated by Django 6.0.6 on 2026-07-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parsha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name_hebrew", models.CharField(max_length=100)),
                ("sefer", models.CharField(max_length=50)),
                ("chapter_verse", models.CharField(max_length=50)),
                ("haftorah_info", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "parshas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReadingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "parsha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="parshas.parsha",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
