# Generated by Django 6.0.6 on 2026-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parshas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingschedule",
            name="hebrew_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
