# Generated by Django 6.0.6 on 2026-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("pro", "Pro Subscribers"),
                            ("free", "Free Users"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                ("recipients_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("email_reports", models.BooleanField(default=True)),
                ("auto_publish_uploads", models.BooleanField(default=False)),
                ("payment_alerts", models.BooleanField(default=True)),
                (
                    "default_upload_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("library_page_size", models.IntegerField(default=24)),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
