# Generated by Django 6.0.8 on 2026-09-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adminnotification_recipients_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
    ]
