# Generated by Django 6.0.6 on 2026-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_usersubscription_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="rc_original_app_user_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
